### ISSUE TITLE
请求联系方式

### ISSUE THREAD

**Issue by iceBear67** [GDWGH/GDWGH#3]
偶然在  yangcong-dl 的 [issues#2](https://github.com/ravizhan/yangcong-dl/issues/2) 里看到您已经下载了若干视频（  
请问能否出于学术研究目的~~白嫖~~分享一份呢，感激不尽（（

**Comment by GuihongWang** [comment]
> 偶然在  yangcong-dl 的 [issues#2](https://github.com/ravizhan/yangcong-dl/issues/2) 里看到您已经下载了若干视频（  
> 请问能否出于学术研究目的~~白嫖~~分享一份呢，感激不尽（（
> 

草 不过只能学术研究目的（

**Comment by GDWGH** [comment]
> 偶然在  yangcong-dl 的 [issues#2](https://github.com/ravizhan/yangcong-dl/issues/2) 里看到您已经下载了若干视频（  
> 请问能否出于学术研究目的~~白嫖~~分享一份呢，感激不尽（（
> 

「洋葱」，点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
提取码: 69s7
链接：https://www.aliyundrive.com/s/Ercra5YVnPA
不能分享或者售卖
～～（个人主页地址缩小到了区 怕他们找到我 而且我云盘分享之前已经实名）～～

**Comment by iceBear67** [comment]
非常感谢！！！

**Comment by GuihongWang** [comment]
email就是最好的联系方式 
当然也可以QQ（除非你是开发者 不会直接加）

**Comment by iceBear67** [comment]
~~主要是没找到你的email~~

**Comment by GuihongWang** [comment]
> ~~主要是没找到你的email~~

重新开启 直到找到解决方案
安卓官方客户端![Screenshot_20220208_171028.jpg](https://user-images.githubusercontent.com/57795156/152954659-9c2a966e-ac90-40dc-94b7-74de756f92fe.jpg)
mac和我的github镜像
![20220204145126.png](https://user-images.githubusercontent.com/57795156/152955428-20dd3c9a-adc9-4ef7-8610-13e114cc0698.png)

**Comment by GuihongWang** [comment]
> ~~主要是没找到你的email~~

已经解决 ~~（github官方安卓客户端）~~
![Screenshot_20220209_205453.jpg](https://user-images.githubusercontent.com/57795156/153205474-01ee46e4-5005-48ca-940b-0cc9fdce0709.jpg)

**Comment by GDWGH** [comment]
~~QQ:2984188181~~
~~上面的信息保持到明天早上9点~~
